<?php

/**
 * Implements hook_views_data_alter().
 */
//function dmpa_taxonomy_validation_views_data() {
//  $data['dmpa_taxonomy_validation']['table']['group'] = t('Global');
//  $data['dmpa_taxonomy_validation']['table']['join'] = [
//    // Exist in all views.
//    '#global' => [],
//  ];
//  $data['dmpa_taxonomy_validation']['field_user_country_target_id'] = [
//    'title' => t('User Country Links'),
//    'help' => t('Outputs country/year/month for a user-based view.'),
//    'field' => [
//      'id' => 'dmpa_term_name',
//    ],
//  ];
//
//  $data['dmpa_taxonomy_validation']['tid'] = [
//    'title' => t('User Country Links'),
//    'help' => t('Outputs country/year/month for a taxonomy-based view.'),
//    'field' => [
//      'id' => 'dmpa_term_name_taxonomy',
//    ],
//  ];
//
//  return $data;
//
//}
